# Generated by Django 5.1.7 on 2025-04-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_usuario_reset_token_alter_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reset_token',
        ),
    ]
