# Generated by Django 5.1.7 on 2025-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_usuario_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
