# Generated by Django 5.1.7 on 2025-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_usuario_reset_token_usuario_reset_token_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='reset_token_expires',
            new_name='token_expira',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
