# Generated by Django 5.1.7 on 2025-04-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_reset_token_expires_usuario_token_expira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_expira',
        ),
    ]
