# Generated by Django 5.1.7 on 2025-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_usuario_options_alter_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='avatars/'),
        ),
    ]
