# Generated by Django 5.1.7 on 2025-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
